import { FormConfig, FormField } from '../../types/form';

export interface AngularSignalCodeResult {
  tsCode: string;
  htmlCode: string;
  combinedCode: string;
}

export function generateAngularSignalFormsCode(config: FormConfig): AngularSignalCodeResult {
  const isMultiStep = config.layoutType === 'multi-step';
  const componentName = `${toPascalCase(config.id)}SignalFormComponent`;

  const flattenedFields: FormField[] = [];
  const steps: FormField[] = [];

  for (const f of config.fields) {
    if (f.type === 'step') {
      steps.push(f);
      if (f.children) flattenedFields.push(...f.children);
    } else {
      flattenedFields.push(f);
    }
  }

  // Generate Signal state for each field
  const signalFieldInits: string[] = [];
  const validationComputeds: string[] = [];

  for (const field of flattenedFields) {
    const defaultVal = getDefaultValue(field);
    signalFieldInits.push(`  // Field: ${field.label}
  readonly ${field.name}Value = signal<any>(${defaultVal});
  readonly ${field.name}Touched = signal<boolean>(false);
  readonly ${field.name}Dirty = signal<boolean>(false);`);

    // Build computed error for this field
    const checks: string[] = [];
    if (field.validation?.required) {
      if (field.type === 'checkbox' || field.type === 'switch') {
        checks.push(`    if (!val) errors.push('${field.validation.requiredMessage || `${field.label} must be checked`}');`);
      } else {
        checks.push(`    if (val === undefined || val === null || String(val).trim() === '') {
      errors.push('${field.validation.requiredMessage || `${field.label} is required`}');
    }`);
      }
    }

    if (field.validation?.emailValidator || field.type === 'email') {
      checks.push(`    if (val && !/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(String(val))) {
      errors.push('Please enter a valid email address');
    }`);
    }

    if (field.validation?.minLength) {
      checks.push(`    if (val && String(val).length < ${field.validation.minLength}) {
      errors.push('Minimum ${field.validation.minLength} characters required');
    }`);
    }

    if (field.validation?.passwordConfirmFieldId) {
      const match = flattenedFields.find(f => f.id === field.validation?.passwordConfirmFieldId);
      if (match) {
        checks.push(`    if (val && val !== this.${match.name}Value()) {
      errors.push('Passwords do not match');
    }`);
      }
    }

    validationComputeds.push(`  readonly ${field.name}Errors = computed<string[]>(() => {
    const val = this.${field.name}Value();
    const errors: string[] = [];
${checks.length ? checks.join('\n') : '    // No validation constraints'}
    return errors;
  });

  readonly ${field.name}Valid = computed(() => this.${field.name}Errors().length === 0);`);
  }

  const allFieldNames = flattenedFields.map(f => f.name);

  const tsCode = `import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Modern Angular Signal Forms Component
 * Generated by NgFormCraft - 100% Signals, computed() validators, zero RxJS leaks!
 */
@Component({
  selector: 'app-${config.id}-signals',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './${config.id}-signals.component.html',
  styleUrls: ['./${config.id}-signals.component.css']
})
export class ${componentName} {
  // Reactive Form State Signals
  readonly isSubmitting = signal(false);
  readonly submittedPayload = signal<Record<string, any> | null>(null);

${signalFieldInits.join('\n\n')}

  // Computed Validation Signals (Signal Forms Architecture)
${validationComputeds.join('\n\n')}

  // Form-level validity derived directly from signal graph
  readonly formErrors = computed<Record<string, string[]>>(() => {
    return {
${allFieldNames.map(name => `      ${name}: this.${name}Errors(),`).join('\n')}
    };
  });

  readonly isFormValid = computed(() => {
    return ${allFieldNames.map(name => `this.${name}Valid()`).join(' && ')};
  });

  readonly formValues = computed(() => ({
${allFieldNames.map(name => `    ${name}: this.${name}Value(),`).join('\n')}
  }));

  // Update Field Value Handler
  updateField(fieldName: string, value: any): void {
    const fieldSignal = (this as any)[\`\${fieldName}Value\`];
    const dirtySignal = (this as any)[\`\${fieldName}Dirty\`];
    if (fieldSignal) {
      fieldSignal.set(value);
      dirtySignal?.set(true);
    }
  }

  // Mark Field Touched Handler
  markTouched(fieldName: string): void {
    const touchedSignal = (this as any)[\`\${fieldName}Touched\`];
    touchedSignal?.set(true);
  }

  // Form Submission
  onSubmit(): void {
    // Touch all signals
${allFieldNames.map(name => `    this.${name}Touched.set(true);`).join('\n')}

    if (!this.isFormValid()) {
      return;
    }

    this.isSubmitting.set(true);
    setTimeout(() => {
      this.isSubmitting.set(false);
      this.submittedPayload.set(this.formValues());
      console.log('Signal Form Submitted:', this.formValues());
    }, 500);
  }
}
`;

  const htmlCode = `<!-- Angular Signal Forms Template -->
<div class="max-w-2xl mx-auto p-6 bg-slate-950 border border-slate-800 rounded-xl text-slate-100">
  <div class="mb-6">
    <h2 class="text-xl font-bold tracking-tight text-white">${escapeHtml(config.title)}</h2>
    <p class="text-xs text-slate-400 mt-1">${escapeHtml(config.description)}</p>
  </div>

  <form (submit)="$event.preventDefault(); onSubmit()" class="space-y-4">
${flattenedFields.map(field => `    <!-- Field: ${field.label} -->
    <div class="space-y-1.5">
      <label class="block text-xs font-medium text-slate-300">
        ${escapeHtml(field.label)}
        ${field.validation?.required ? '<span class="text-rose-400">*</span>' : ''}
      </label>
      <input
        type="${field.type === 'password' ? 'password' : field.type === 'number' ? 'number' : 'text'}"
        [value]="${field.name}Value()"
        (input)="updateField('${field.name}', $any($event.target).value)"
        (blur)="markTouched('${field.name}')"
        placeholder="${escapeHtml(field.placeholder || '')}"
        class="w-full px-3 py-2 text-xs bg-slate-900 border border-slate-800 rounded-lg text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-rose-500"
      />
      <!-- Signal Error Display: ${field.name}Errors() -->
      @if (${field.name}Touched() && ${field.name}Errors().length) {
        <p class="text-[11px] text-rose-400 font-mono flex items-center gap-1">
          <span>●</span>
          <span>{{ ${field.name}Errors()[0] }}</span>
        </p>
      }
    </div>`).join('\n\n')}

    <div class="pt-4 border-t border-slate-800 flex items-center justify-between">
      <span class="text-xs font-mono text-slate-400">
        Status: {{ isFormValid() ? 'VALID' : 'INVALID' }}
      </span>
      <button
        type="submit"
        [disabled]="isSubmitting()"
        class="px-5 py-2 text-xs font-semibold text-white bg-rose-600 rounded-lg hover:bg-rose-500 disabled:opacity-50 transition-colors"
      >
        {{ isSubmitting() ? 'Submitting...' : '${escapeHtml(config.submitButtonText)}' }}
      </button>
    </div>
  </form>
</div>
`;

  return {
    tsCode,
    htmlCode,
    combinedCode: `// ================= ${config.id}-signals.component.ts =================\n\n${tsCode}\n\n<!-- ================= ${config.id}-signals.component.html ================= -->\n\n${htmlCode}`,
  };
}

function getDefaultValue(field: FormField): string {
  if (field.defaultValue !== undefined) {
    if (typeof field.defaultValue === 'string') return `'${field.defaultValue}'`;
    return String(field.defaultValue);
  }
  if (field.type === 'checkbox' || field.type === 'switch') return 'false';
  if (field.type === 'number' || field.type === 'slider' || field.type === 'rating') return '0';
  return "''";
}

function toCamelCase(str: string): string {
  return str.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function escapeHtml(str: string): string {
  return str.replace(/"/g, '&quot;');
}
