import { FormConfig, FormField } from '../../types/form';
import { generateZodSchema } from './zodSchemaGenerator';

export function generateTanStackAngularCode(config: FormConfig): string {
  const componentName = `${toPascalCase(config.id)}TanStackComponent`;
  const schemaName = `${toCamelCase(config.id)}Schema`;

  const flattenedFields: FormField[] = [];
  for (const f of config.fields) {
    if (f.type === 'step' && f.children) {
      flattenedFields.push(...f.children);
    } else {
      flattenedFields.push(f);
    }
  }

  const defaultValuesObj = flattenedFields.reduce((acc, f) => {
    let val = "''";
    if (f.defaultValue !== undefined) {
      val = typeof f.defaultValue === 'string' ? `'${f.defaultValue}'` : `${f.defaultValue}`;
    } else if (f.type === 'checkbox' || f.type === 'switch') {
      val = 'false';
    } else if (f.type === 'number' || f.type === 'slider' || f.type === 'rating') {
      val = '0';
    } else if (f.type === 'formarray') {
      val = '[]';
    }
    acc.push(`      ${f.name}: ${val}`);
    return acc;
  }, [] as string[]).join(',\n');

  return `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { injectForm, TanStackField } from '@tanstack/angular-form';
import { zodValidator } from '@tanstack/zod-form-adapter';
import { ${schemaName}, type ${toPascalCase(config.id)}FormData } from './${config.id}.schema';

/**
 * Modern Angular Component powered by @tanstack/angular-form
 * Generated by NgFormCraft (tancn.dev for Angular)
 */
@Component({
  selector: 'app-${config.id}-tanstack',
  standalone: true,
  imports: [CommonModule, TanStackField],
  template: \`
    <div class="max-w-2xl mx-auto p-6 bg-slate-950 border border-slate-800 rounded-xl text-slate-100">
      <div class="mb-6">
        <h2 class="text-xl font-bold tracking-tight text-white">${escapeHtml(config.title)}</h2>
        <p class="text-xs text-slate-400 mt-1">${escapeHtml(config.description)}</p>
      </div>

      <form
        (submit)="form.handleSubmit($event)"
        class="space-y-4"
      >
${flattenedFields.map(f => renderTanStackFieldTemplate(f)).join('\n')}

        <div class="pt-4 border-t border-slate-800 flex justify-end">
          <button
            type="submit"
            class="px-5 py-2 text-xs font-semibold text-white bg-rose-600 rounded-lg hover:bg-rose-500 transition-colors"
          >
            ${escapeHtml(config.submitButtonText)}
          </button>
        </div>
      </form>
    </div>
  \`
})
export class ${componentName} {
  readonly form = injectForm({
    defaultValues: {
${defaultValuesObj}
    },
    validatorAdapter: zodValidator(),
    validators: {
      onChange: ${schemaName},
    },
    onSubmit: async ({ value }) => {
      console.log('TanStack Angular Form Submitted:', value);
    },
  });
}
`;
}

function renderTanStackFieldTemplate(field: FormField): string {
  if (field.type === 'checkbox' || field.type === 'switch') {
    return `        <!-- Field: ${field.label} -->
        <ng-container [tanstackField]="form" name="${field.name}">
          <ng-template let-field>
            <div class="flex items-center gap-2">
              <input
                type="checkbox"
                [checked]="field.state.value"
                (change)="field.handleChange($any($event).target.checked)"
                class="rounded border-slate-700 bg-slate-900 text-rose-600 focus:ring-rose-500"
              />
              <label class="text-xs text-slate-300">${escapeHtml(field.label)}</label>
            </div>
            @if (field.state.meta.errors.length) {
              <p class="text-[11px] text-rose-400 mt-1">{{ field.state.meta.errors[0] }}</p>
            }
          </ng-template>
        </ng-container>`;
  }

  return `        <!-- Field: ${field.label} -->
        <ng-container [tanstackField]="form" name="${field.name}">
          <ng-template let-field>
            <div class="space-y-1">
              <label class="block text-xs font-medium text-slate-300">
                ${escapeHtml(field.label)}
                ${field.validation?.required ? '<span class="text-rose-400">*</span>' : ''}
              </label>
              <input
                type="${field.type === 'datepicker' ? 'date' : field.type === 'number' ? 'number' : field.type === 'password' ? 'password' : 'text'}"
                [value]="field.state.value"
                (input)="field.handleChange($any($event).target.value)"
                (blur)="field.handleBlur()"
                placeholder="${escapeHtml(field.placeholder || '')}"
                class="w-full px-3 py-2 text-xs bg-slate-900 border border-slate-800 rounded-lg text-slate-100 placeholder:text-slate-500 focus:outline-none focus:border-rose-500"
              />
              @if (field.state.meta.errors.length) {
                <p class="text-[11px] text-rose-400">{{ field.state.meta.errors[0] }}</p>
              }
            </div>
          </ng-template>
        </ng-container>`;
}

function toCamelCase(str: string): string {
  return str.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function escapeHtml(str: string): string {
  return str.replace(/"/g, '&quot;');
}
