import { FormConfig, FormField } from '../../types/form';

export function generateZodSchema(config: FormConfig): string {
  const schemaFields: string[] = [];

  function processField(field: FormField, indent: string = '  '): string {
    const lines: string[] = [];

    if (field.type === 'formarray' && field.children) {
      const childProps = field.children.map(c => processField(c, indent + '    ')).join(',\n');
      const minCount = field.arrayConfig?.minItems ?? 0;
      let arrayValidator = `z.array(\n${indent}  z.object({\n${childProps}\n${indent}  })\n${indent})`;
      if (minCount > 0) {
        arrayValidator += `.min(${minCount}, { message: "Must have at least ${minCount} items" })`;
      }
      return `${indent}${field.name}: ${arrayValidator}`;
    }

    if (field.type === 'step' && field.children) {
      return field.children.map(c => processField(c, indent)).join(',\n');
    }

    if (field.type === 'fieldgroup' && field.children) {
      const groupProps = field.children.map(c => processField(c, indent + '  ')).join(',\n');
      return `${indent}${field.name}: z.object({\n${groupProps}\n${indent}})`;
    }

    let rule = 'z.string()';

    switch (field.type) {
      case 'number':
      case 'slider':
      case 'rating':
        rule = 'z.number()';
        if (field.validation?.min !== undefined) {
          rule += `.min(${field.validation.min}, { message: "Minimum value is ${field.validation.min}" })`;
        }
        if (field.validation?.max !== undefined) {
          rule += `.max(${field.validation.max}, { message: "Maximum value is ${field.validation.max}" })`;
        }
        break;

      case 'email':
        rule = 'z.string().email({ message: "Invalid email format" })';
        break;

      case 'checkbox':
      case 'switch':
        rule = 'z.boolean()';
        if (field.validation?.required) {
          rule += `.refine(val => val === true, { message: "${field.validation.requiredMessage || 'Must be checked'}" })`;
        }
        break;

      case 'multiselect':
        rule = 'z.array(z.string())';
        if (field.validation?.required) {
          rule += `.min(1, { message: "Select at least one option" })`;
        }
        break;

      default:
        // text, password, textarea, select, radio, datepicker, url, phone
        if (field.validation?.required) {
          rule += `.min(1, { message: "${field.validation.requiredMessage || `${field.label} is required`}" })`;
        } else {
          rule += '.optional()';
        }
        if (field.validation?.minLength) {
          rule += `.min(${field.validation.minLength}, { message: "Minimum length is ${field.validation.minLength}" })`;
        }
        if (field.validation?.maxLength) {
          rule += `.max(${field.validation.maxLength}, { message: "Maximum length is ${field.validation.maxLength}" })`;
        }
        if (field.validation?.pattern) {
          rule += `.regex(new RegExp("${field.validation.pattern}"), { message: "${field.validation.patternMessage || 'Invalid format'}" })`;
        }
        break;
    }

    return `${indent}${field.name}: ${rule}`;
  }

  // Collect all fields (flatten steps if multi-step)
  for (const field of config.fields) {
    if (field.type === 'step' && field.children) {
      for (const child of field.children) {
        schemaFields.push(processField(child));
      }
    } else {
      schemaFields.push(processField(field));
    }
  }

  // Cross-field validations (e.g. password confirm)
  const passwordConfirmRefines: string[] = [];
  const allFlattenedFields: FormField[] = [];
  for (const f of config.fields) {
    if (f.type === 'step' && f.children) {
      allFlattenedFields.push(...f.children);
    } else {
      allFlattenedFields.push(f);
    }
  }

  for (const field of allFlattenedFields) {
    if (field.validation?.passwordConfirmFieldId) {
      const target = allFlattenedFields.find(f => f.id === field.validation?.passwordConfirmFieldId);
      if (target) {
        passwordConfirmRefines.push(
          `.refine((data) => data.${target.name} === data.${field.name}, {\n` +
          `  message: "Passwords do not match",\n` +
          `  path: ["${field.name}"],\n` +
          `})`
        );
      }
    }
  }

  return `import { z } from 'zod';

/**
 * Zod Schema for "${config.title}"
 * Generated by NgFormCraft (tancn.dev for Angular)
 */
export const ${toCamelCase(config.id)}Schema = z.object({
${schemaFields.join(',\n')}
})${passwordConfirmRefines.join('')};

export type ${toPascalCase(config.id)}FormData = z.infer<typeof ${toCamelCase(config.id)}Schema>;
`;
}

function toCamelCase(str: string): string {
  return str.replace(/[-_](\w)/g, (_, c) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}
